name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare deploy directory
        run: |
          # create a clean folder for files to publish
          rm -rf public || true
          mkdir public
          # copy files we want to publish, excluding git, workflows, node deps, tests
          rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='__tests__' --exclude='*.ps1' --exclude='*.md' ./ public/
          ls -la public

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
